version: '3.8'
services:
  logbot:
    container_name: LogBot
    image: theprogrammershangout/logbot:latest
    volumes:
      - type: bind
        source: ./config
        target: /config
    restart: always
    env_file:
      - .env